# @package _global_
tune:
  model:
    transpose:
      - true
      # - false
    br_act:
      - true
      # - false
    ema_y:
      - true
      # - false
    balancing:
      - mine-shuffle
    recursive:
      - true
    init:
      - 0.001
    hiddens_G_x:
      - 
        - 16
      # - 
      #   - 32
    hiddens_G_y:
      # - 
      #   - 16
      - 
        - 32
    br_size:
      - 32
      # - 64
      # - 24
      # - 44
    transpose_size:
      - 64
    hiddens_D_net:
      - 
        - 16
      # - 
      #   - 8
      # - 
      #   - 32
      # - 
      #   - 12
    num_channels_hidden:
      - 
        - ${model.br_size}
        - ${model.br_size}
        # - ${model.br_size}
    num_channels_hidden_x:
     - 
        - ${model.br_size}
        - ${model.br_size}
        - ${model.br_size}
    num_channels_hidden_y:
      - 
        - ${model.br_size}
        - ${model.br_size}
        - ${model.br_size}
  exp:
    lambda_D:
      - 0.01
      - 0
    lambda_X:
      # - 0.1
      # - 0.01
      # - 0.02
      - 0.05
    epochs:
      # - 400
      # - 500
      # - 600
      # - 800
      - 500
      # - 500
    patience:
      - 500
    lr:
      # - 1.e-3
      # - 2.e-3
      - 5.e-3
      - 1.e-2
    batch_size:
      # - 128
      - 64
    update_lambda_D:
      - True
      # - False
    beta:
      - 0.999
      # - 0.99
    dropout:
      # - 0.2
      - 0.1
    # dropout_x:
    #   - 0.1
    #   - 0.2
    weight_decay:
      - 5.e-5
      - 1.e-4
      - 1.e-5
    weight_decay_D:
      - 0
      # - 1.e-5
    lr_D:
      - 1.e-4
      - 2.e-4
      - 5.e-4
      - 1.e-3
exp:
  mode: tune