# @package _global_
tune:
  model:
    num_sins: 
      # - 0
      # - 1
      # - 2
      - 3
      - 5
      # - 7
    use_global:
      - True
      # - False
    
    # num_poly: 
    #   - 0
    #   - 2
    #   - 4
    #   - 6
    # num_exp: 
    #   - 0
    #   - 2
    #   - 4
    #   - 6
    # koopman_dim_add:
    #   - 4
    #   - 8
    #   - 16
    #   - 24
    d_model: 
      - 20
      # - 24
      # - 28
    koopman_dim_add:
      - 20
      # - 24
      # - 28

    
    hiddens_G_y: 
      - 
        - 32
      # - 
      #   - 24
      # -
      #   - 16
    hiddens_G_x:
      - 
        - 32
      # - 
      #   - 24
      # -
      #   - 16

  exp:
    lambda_D:
      - 0.1
      - 0.2
      - 0.05
    lambda_X:
      - 0.1
      - 0.05
    dropout:
      # - 0.1
      - 0.2
      - 0.3
      # - 0.4
    weight_decay: 
      - 1.e-5
      # - 1.e-6
      # - 2.e-5
      - 1.e-4
      
    update_freq:
      - 50
      - 100
      # - -1
      # - 150
      # - 50
    epoch_w:
      - 5
      - 10
    batch_size: 
      - 64
      # - 128
      # - 256
    lr:
      - 1.e-2
      # - 2.e-3
      # - 1.e-3
    update_lambda_D:
      - True
      # - False
    
    
exp:
  mode: tune
  gpu_resources: 0.5
  cpu_resources: 5
  records_exp:
    - update_freq
  