# @package _global_
tune:
  model:
    transpose:
      - true
      # - false
    br_act:
      - true
      # - false
    ema_y:
      - true
      # - false
    balancing:
      - mine-shuffle
    recursive:
      - true
    init:
      - 0.001
    hiddens_G_x:
      - 
        - 16
    hiddens_G_y:
      - 
        - 16
    br_size:
      - 32
    transpose_size:
      - 64
    hiddens_D_net:
      - 
        - 16
      # - 
      #   - 8
      # - 
      #   - 32
      # - 
      #   - 64
    # kernel_size:
    #   - 2
    #   - 3
    # kernel_size_x:
    #   - 2
    #   - 3
    # kernel_size_y:
    #   - 2
    #   - 3
    #   - 1
    
  exp:
    lambda_D:
      - 0.01
    lambda_X:
      - 0.1
    epochs:
      # - 300
      - 500
      # - 600
      # - 800
      # - 400
      # - 300
    patience:
      - 500
    lr:
      - 1.e-3
      # - 5.e-4
    batch_size:
      - 128
    update_lambda_D:
      - True
      # - False
    beta:
      - 0.999
    dropout:
      # - 0.2
      - 0.1
    # dropout_x:
    #   - 0.1
    #   - 0.2
    weight_decay:
      - 5.e-5
      - 1.e-4
      - 1.e-5
      - 2.e-4
    weight_decay_D:
      - 0
      # - 1.e-5
    lr_D:
      # - 2.e-4
      - 1.e-4
exp:
  mode: tune