# @package _global_
model:
  balancing: mine-shuffle
  br_act: true
  br_size: 32
  ema_y: true
  hiddens_D_net:
  - 16
  hiddens_G_x:
  - 32
  hiddens_G_y:
  - 32
  init: 0.001
  recursive: true
  transpose: true
  transpose_size: 64
  num_sins: 3
  d_model: 24
  koopman_dim_add: 24

exp:
  batch_size: 64
  beta: 0.999
  dropout: 0.2
  epochs: 500
  lambda_D: 0.1
  lambda_X: 0.1
  lr: 0.01
  lr_D: 0.0002
  patience: 500
  update_lambda_D: true
  weight_decay: 1.0e-04
  weight_decay_D: 0
  update_freq: 50