# @package _global_

model:
  ema_y: true
  hiddens_D_net:
  - 16
  hiddens_G_x:
  - 16
  hiddens_G_y:
  - 16
  init: 0.001
  transpose: False
  transpose_size: 64
  d_model: 28
  koopman_dim_add: 28
  num_sins: 7
  
exp:
  batch_size: 64
  beta: 0.999
  dropout: 0.2
  epochs: 500
  lambda_D: 0.2
  lambda_X: 0.1
  lr: 0.01
  lr_D: 0.0001
  patience: 500
  update_lambda_D: true
  weight_decay: 2.e-05
  weight_decay_D: 0
