# @package _global_
dataset:
  coeff: 0

model:
  init: 0.001
  d_model: 12
  hiddens_G_y:
    - 32
  use_global: true

exp:
  batch_size: 128
  epochs: 150
  lambda_D: 0.1
  lr: 0.001
  update_lambda_D: true
  weight_decay: 1.0e-06
  weight_decay_D: 0
  update_freq: 50
  epoch_w: 5
  dropout: 0.0
